### ISSUE TITLE
Determine guide sections

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/content-guide-uswds#4]
The existing version of the content guide has four sections, for which I created collections in this repo. We should determine if these sections still make sense, or how we might want to change the structure.

```
collections_dir: sections

collections: 
  introduction:
    output: true
    permalink: /introduction/:path/
  content_types:
    output: true
    permalink: /content-types/:path/
  our_approach:
    output: true
    permalink: /our-approach/:path/
  our_style:
    output: true
    permalink: /our-style/:path/ 
```
